apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bjj-api
  namespace: bjj-app
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: bjj-api
  endpoints:
    - port: http
      path: /metrics
      interval: 30s