apiVersion: v1
kind: ServiceAccount
metadata:
  name: bjj-api-sa
  namespace: bjj-app
  annotations:
    # This links the K8s service account to the AWS IRSA role created by Terraform.
    # The pod inherits permission to call Secrets Manager via this annotation.
    eks.amazonaws.com/role-arn: arn:aws:iam::380847574744:role/bjj-irsa-role
